version: "3"
services:
  ui:
    container_name: frontend
    restart: always
    build: ./client
    ports:
      - "8081:8081"
    volumes:
      - ./client/src:/app/src
      - ./client/tests:/app/tests
      - ./client/coverage:/client/coverage
    links:
      - api
  api:
    container_name: backend
    restart: always
    build: ./api
    ports:
        - "3001:3001"
    volumes:
      - ./api/src:/app/src
      - ./api/tests:/app/tests
      - ./api/coverage:/app/coverage
    depends_on: 
      - mongo
    environment:
      - DATABASE_URL=mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
